; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-1602]
platform = espressif32@6.9.0
platform_packages = framework-arduinoespressif32 @ ~3.20017.0
board = esp32-1602
framework = arduino
board_upload.flash_size = 16MB

upload_speed = 921600
monitor_speed = 115200

lib_deps =
  FastLED
  ArduinoJson
  libsodium
  zlib_turbo

build_flags =
  !python -X utf8 ./script/genrate_version.py       ; 版本号
  -D DEFAULT_LOG_LEVEL=LOG_LEVEL_INFO
  -D CORE_DEBUG_LEVEL=3
  -I include


[env:esp32s3-1602-dev]
platform = espressif32@6.12.0
platform_packages = framework-arduinoespressif32 @ ~3.20017.0
board = esp32-1602
framework = arduino
board_upload.flash_size = 16MB

upload_speed = 921600
monitor_speed = 115200

lib_deps =
  FastLED
  ArduinoJson
  libsodium
  zlib_turbo

; 调试模式配置
build_type = debug        ; 启用调试模式
debug_tool = esp-builtin  ; 使用内置调试工具
debug_init_break = tbreak setup ; 在setup函数处断点

build_flags =
  !python -X utf8 ./script/genrate_version.py       ; 版本号
  -D DEFAULT_LOG_LEVEL=LOG_LEVEL_VERBOSE
  -D CORE_DEBUG_LEVEL=5
  -O0
  -g3
  -ggdb
  -I include

build_unflags =
  -O2                              ; 移除O2优化
  -Os                              ; 移除尺寸优化

monitor_filters = 
  default
  time
  esp32_exception_decoder


[env:esp32s3-1602-test]
platform = espressif32@6.12.0
platform_packages = framework-arduinoespressif32 @ ~3.20017.0
board = esp32-1602
framework = arduino
board_upload.flash_size = 16MB

test_build_src = yes
test_speed = 115200
upload_speed = 921600
monitor_speed = 115200

build_src_filter = 
  +<*>
  -<main.cpp>

lib_deps =
  FastLED
  ArduinoJson
  libsodium
  zlib_turbo

monitor_filters = 
  default
  time
  esp32_exception_decoder

build_flags =
  !python -X utf8 ./script/genrate_version.py       ; 版本号
  -D DEFAULT_LOG_LEVEL=LOG_LEVEL_VERBOSE
  -D CORE_DEBUG_LEVEL=5
  -O0
  -g3
  -ggdb
  -I include

build_unflags =
  -O2                              ; 移除O2优化
  -Os                              ; 移除尺寸优化