; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-1602]
platform = espressif32@6.9.0
board = esp32-1602
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
upload_speed = 921600
monitor_speed = 115200

lib_deps =
  FastLED
  ArduinoJson
  libsodium
  zlib_turbo

build_flags =
  !python -X utf8 ./script/genrate_version.py       ; 版本号
  -D DEFAULT_LOG_LEVEL=LOG_LEVEL_INFO
  -D CORE_DEBUG_LEVEL=3
  -I include


[env:esp32s3-1602-dev]
platform = espressif32@6.12.0
board = esp32-1602
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

upload_speed = 921600
monitor_speed = 115200

lib_deps =
  FastLED
  ArduinoJson
  libsodium
  zlib_turbo

; 调试模式配置
build_type = debug        ; 启用调试模式
debug_tool = esp-builtin  ; 使用内置调试工具
debug_init_break = tbreak setup ; 在setup函数处断点

build_flags =
  !python -X utf8 ./script/genrate_version.py       ; 版本号
  -D DEFAULT_LOG_LEVEL=LOG_LEVEL_INFO
  -D CORE_DEBUG_LEVEL=2
  -D ENABLE_COREDUMP_ON_FATAL=1
  -O0
  -g3
  -ggdb
  -I include
  
  ; OPI PSRAM 配置
  -D BOARD_HAS_PSRAM
  -D CONFIG_SPIRAM_MODE_OCT=1
  -D CONFIG_SPIRAM_SPEED=80
  -D CONFIG_SPIRAM=1
  -D CONFIG_SPIRAM_SIZE=8388608
  
  ; SPI Flash 驱动配置
  -D CONFIG_SPI_FLASH_VERIFY_WRITE=1      ; 启用写入验证
  -D CONFIG_SPI_FLASH_LOG_FAILED_WRITE=1  ; 记录写入失败
  -D CONFIG_SPI_FLASH_WARN_SETTING_ZERO_TO_ONE=1  ; 警告异常写入

build_unflags =
  -O2                              ; 移除O2优化
  -Os                              ; 移除尺寸优化

monitor_filters = 
  default
  time
  esp32_exception_decoder


[env:esp32s3-1602-test]
platform = espressif32@6.12.0
#platform_packages = framework-arduinoespressif32 @ ~3.20017.0
board = esp32-1602
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

test_build_src = yes
test_speed = 115200
upload_speed = 921600
monitor_speed = 115200

build_src_filter = 
  +<*>
  -<main.cpp>

lib_deps =
  FastLED
  ArduinoJson
  libsodium
  zlib_turbo

monitor_filters = 
  default
  time
  esp32_exception_decoder

build_flags =
  !python -X utf8 ./script/genrate_version.py       ; 版本号
  -D DEFAULT_LOG_LEVEL=LOG_LEVEL_DEBUG
  -D CORE_DEBUG_LEVEL=5
  -O0
  -g3
  -ggdb
  -I include
  
  ; OPI PSRAM 配置
  -D BOARD_HAS_PSRAM
  -D CONFIG_SPIRAM_MODE_OCT=1
  -D CONFIG_SPIRAM_SPEED=80
  -D CONFIG_SPIRAM=1
  -D CONFIG_SPIRAM_SIZE=8388608

build_unflags =
  -O2                              ; 移除O2优化
  -Os                              ; 移除尺寸优化



;pio run --target uploadfs